### ISSUE TITLE
contributes setting not working

### ISSUE THREAD

**Issue by bkelley13** [octref/simple-customdata#3]
I think the issue that really prompted my question is that I'm not seeing the contributes setting working.  I tried it with relative and absolute settings, and in both cases, the file is not getting used.  The same file works with workspace settings.  

    "html": {
            "experimental": {
              "customData": [
                "./jet-components.json"
              ]
            }
          }

I also tried an absolute path, /tmp/...json, but in neither case did it work for me.  I tried on win and mac systems, with latest vsce and 1.31.  Is this setting working for you? 

_Originally posted by @bkelley13 in https://github.com/octref/simple-customdata/issues/2#issuecomment-461928862_

**Comment by bkelley13** [comment]
I tried upgrading to latest code generator, vsce, but still the above setting isn't being used in my extension.  Any suggestions?  I'd love to use this for our html tag lookups extenion for oracle jet.  (the previous 1.30 data tags were great and we used them, and this new attribute enumeration lookup is so promising for us.)

**Comment by octref** [comment]
@bkelley13 Sorry, there was a bug. I just opened https://github.com/Microsoft/vscode/issues/68554 and pushed for a fix. You should be able to test it in Insiders tomorrow.

**Comment by bkelley13** [comment]
Awesome, thank you.
