### ISSUE TITLE
Slot support

### ISSUE THREAD

**Issue by zavr-1** [octref/simple-customdata#4]
Please implement slot support? Do I define what I want to be inside of the parent element just in the description? E.g., `<my-description>{title}</my-description>`
```
{
  "version": 1,
  "tags": [{
    "name": "my-description",
    "description": "The description. Place children for display.",
    "attributes": []
  }]
}
```

**Comment by octref** [comment]
What slot are you referring to? What you wrote doesn't look like web component's slots.

**Comment by zavr-1** [comment]
@octref sorry maybe it's not called slots, I mean the data inside of the tag -- is it possible to document it? In _React_ it's called children but it's just a separate attribute that can have documentation. 

For example, for 

```html
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
  Your browser does not support the video tag.
</video>
```

I would write documentation for "content/children" like "Sources and fall-back." 

Maybe it's not part of web components though. Also to not start the new topic, could it be possible to enable the customdata suggestions functionality in other languages such as markdown since it can have html tags?

**Comment by octref** [comment]
In that case doesn't `"description"` already serve your purpose? Just make it 2 paragraphs, 1st explaining the element and 2nd describing what children should be passed in.

**Comment by zavr-1** [comment]
OK thanks 👍
